name: ChatGPT Codex Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  codex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run ChatGPT Codex
        uses: openai/chatgpt-codex-action@v1
        with:
          prompt: "Revisa el código en este repo y sugiere mejoras o funciones adicionales."
          github-token: ${{ secrets.GITHUB_TOKEN }}
